version: "2"

run:
  timeout: 5m

# Standard 1: Top-level settings for our custom team rules
linters-settings:
  revive:
    rules:
      - name: var-declaration
      - name: error-return
      - name: error-strings
  
  wrapcheck:
    ignorePackageSignatures:
      - .Check(.*)

  gocognit:
    min-complexity: 15

# Standard 2: Explicitly enable the chosen "Level 3" toolset
linters:
  enable:
    - errcheck  
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - revive      # Team standard: Dependency Injection
    - wrapcheck   # Team standard: Observability
